adds Ruby 3.0 to CI, drops Ruby 2.2 support (#104)
New Rubocop, New Appeasements:

* rename Lint/HandleExceptions

    Error: The `Lint/HandleExceptions` cop has been renamed to
    `Lint/SuppressedException`.

* disable Style/FrozenStringLiteralComment

* Style/RedundantReturn

Opting to disable the check for this case statement because it is twisty
and the explicit returns are more clear than depending on the case
statement and the lines within remain the final statements in future
changes.

* Style/NumericPredicate

    Use number.negative? instead of number < 0.

Sure.

* Style/SafeNavigation

    Use safe navigation (&.) instead of checking if an object exists
    before calling the method.

OK.

* Lint/RaiseException

    Use StandardError over Exception.

OK. Except these errors are all more RuntimeException flavored which is
the default type of exception when raising.